server:
  port: 8081

logging:
  level:
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: tp-user-profile-api

#management:
#  tracing:
#    sampling:
#      probability: 1.0

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/multilingualblogging
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
