server:
  port: 8081

logging:
  level:
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: tp-user-profile-api
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/multilingualblogging
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL57Dialect
#    show-sql: true
  datasource:
    url: jdbc:h2:mem:csdb
    driver-class-name: org.h2.Driver
    username: root
    password: examly
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

management:
  tracing:
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
