server:
  port: 8084

logging:
  level:
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: tp-language-management-api

#management:
#  tracing:
#    sampling:
#      probability: 1.0

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
